# `=== Atelier Scikit-learn ===`

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")

# Exploration du dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

## `Partie 1 – Gestion des doublons`

### `1.1: Vérification de l’existence de doublons dans df`

In [10]:
print(f" Duplications: {df.duplicated().sum()}")

 Duplications: 5

### `1.2: Suppression des doublons`

In [13]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

### `1.3: gestion des Valeurs manquantes`

In [14]:
df.isna().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     6
humidite        5
pression        5
consommation    5
etat            4
dtype: int64

In [15]:
# Statistiques descriptives
df.describe()

       temperature    humidite     pression  consommation
count   594.000000  595.000000   595.000000    595.000000
mean     24.896212   64.863395  1012.241059    208.693294
std       4.068454   10.760478    10.623413     72.320179
min     -18.500000   28.520000   850.000000     18.120000
25%      22.597500   58.090000  1006.890000    160.500000
50%      24.870000   65.370000  1012.960000    206.130000
75%      27.295000   71.590000  1017.835000    254.265000
max      58.700000  145.000000  1038.430000    875.000000

In [16]:
# Gestion des veleurs manquantes pour la variable numeriques
# colonne température
df['temperature'] = df['temperature'].fillna(df['temperature'].median())
# Colonne consommation
df['consommation'] = df['consommation'].fillna(df['consommation'].median())
# Colonne humidite
df['humidite'] = df['humidite'].fillna(df['humidite'].median())
# Colonne pression
df['pression'] = df['pression'].fillna(df['pression'].median())
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     600 non-null    str
 1   date_heure    600 non-null    str
 2   id_capteur    600 non-null    str
 3   batiment      600 non-null    str
 4   temperature   600 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          596 non-null    str
dtypes: float64(4), str(5)
memory usage: 46.9 KB

In [17]:
# Gestion des veleurs manquantes pour la variable numeriques
df["etat"].mode()

0    OK
Name: etat, dtype: str

In [18]:
df["etat"] = df["etat"].fillna("OK")
df.isnull().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     0
humidite        0
pression        0
consommation    0
etat            0
dtype: int64

## `Partie 2 – Sélection de y (cible) et X (caractéristiques)`

### `2.1: On définit "etat" comme la cible ou valeur à prédire et "temperature", "humidite", "pression" et "consommation" comme caractéristiques ou variables explicatives`

`Selection des features`

In [25]:
X = df[['temperature', 'humidite', 'pression', 'consommation']]

`Selection des labels`

In [26]:
y = df[['etat']]

### `2.2: Affichage des cinq premières lignes de X et de y`

In [27]:
X.head()

   temperature  humidite  pression  consommation
0        25.46     58.06   1008.95        287.28
1        24.00     79.73    993.39        116.20
2        25.82     54.47   1010.32        288.50
3        28.23     69.39   1019.62        136.65
4        20.58     53.80   1016.58        182.62

In [28]:
y.head()

  etat
0   OK
1   OK
2   OK
3   OK
4   OK

### `2.3: Quel est le type du problème de machine learning ?`

Le type de problème en question est un problème de classification, l'objectif est de classer les enreigistrements dans les classe: `OK`, `ALERTE` et `ERREUR` en fontion des valeurs de la temperature, de l'humidité, de la pression et de la consommation

## `Partie 3 – Découpage Train/Test`

#### `3.1:` Division de `X `en deux ensembles distincts : un pour l'entraînement `(train)` et un pour le test `(test)`. Avec les conditions suivantes : `20%` des données serviront au test ; garantir la `reproductibilité` du découpage ; conserver les mêmes `proportions de classes` dans l'ensemble de `train` et de `test` que dans les données d'origine`

In [33]:
from sklearn.model_selection import train_test_split

# Division en train et test des features et labels
X_train, X_test, y_train, y_test = train_test_split(
     X,                  # Features
     y,                  # Target
     test_size=0.2,      # 20% des données pour le test
     random_state=42,    # Garantir la reproductibilité du découpage
     stratify=y          # conserver les meme proportions de classe dans train et test
)

## `Partie 4 – Gestion des valeurs manquantes`

### `4.1: Vérification de l’existence de valeurs manquantes`

In [29]:
X.isnull().sum()

temperature     0
humidite        0
pression        0
consommation    0
dtype: int64

### `4.2: Sélection de SimpleImputer avec la médiane`

In [34]:
from sklearn.impute import SimpleImputer

# Instanciation de l'imputeur
imputer = SimpleImputer(strategy="median")
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

### `4.3: Qu’est ce qui justifie le choix de la médiane ?`

Le dataset en question contient des outliers (valeurs abérantes) et cela influx sur le calcul de la moyenne et de la variance, et pas sur la mediane; ce qui justifie le choix de la médiane

### `4.4: Les paramètres (médianes) de l’imputeur sur X_train`

In [54]:
medianes = imputer.statistics_

for col, med in zip(X_train.columns, medianes):
     print(f"{col}  --- : {med:.4f}")

temperature  --- : 24.8700
humidite  --- : 65.3350
pression  --- : 1012.6700
consommation  --- : 206.1300

### `4.5: On déterminer X_train_imputed et X_test_imputed, les transformés de X_train et X_test`

In [37]:
X_train_imputed

array([[  58.7 ,   81.51, 1026.79,  271.92],
       [  26.2 ,   76.27, 1016.74,  191.33],
       [  27.27,   75.68, 1013.78,  335.2 ],
       ...,
       [  21.64,   52.74, 1002.78,  157.77],
       [  26.27,   68.79, 1003.12,  244.9 ],
       [  32.72,   53.28, 1010.05,  195.37]], shape=(480, 4))

In [38]:
X_test_imputed

array([[  19.27,   58.39, 1003.74,  136.56],
       [  25.96,   62.79, 1012.17,  228.74],
       [  24.87,   69.97, 1014.14,  181.07],
       [  33.29,   50.43, 1009.87,  356.76],
       [  30.38,   65.98, 1005.48,  256.18],
       [  27.85,   58.01, 1012.29,  208.09],
       [  26.04,   67.17, 1011.38,  253.99],
       [  28.66,   35.83, 1022.52,  142.86],
       [  25.02,   79.27, 1027.7 ,  214.88],
       [  20.71,   72.01, 1002.15,  144.24],
       [  24.86,   68.77, 1003.98,  289.79],
       [  25.91,   49.2 , 1016.57,  201.37],
       [  29.5 ,   81.47, 1015.48,  256.53],
       [  27.33,   89.45, 1001.98,  346.24],
       [  22.96,   42.4 , 1011.47,  142.67],
       [  23.64,   48.79,  994.25,  222.42],
       [  20.72,   75.27,  997.63,  230.8 ],
       [  22.79,   68.34, 1013.41,  115.55],
       [  30.92,   67.19, 1009.71,  329.78],
       [  26.06,   77.13, 1021.87,  108.36],
       [  29.97,   68.65, 1007.19,  267.37],
       [  24.3 ,   58.75, 1023.6 ,  244.86],
       [  25.11,   60.07, 1028.48,  180.6 ],
       [  18.32,   67.17, 1025.6 ,  201.99],
       [  24.24,   69.31, 1030.13,  131.71],
       [  30.37,   64.55,  997.31,  311.77],
       [  30.24,   62.06, 1009.35,  299.69],
       [  25.93,   61.05, 1012.96,  172.65],
       [  24.  ,   79.73,  993.39,  116.2 ],
       [  24.34,   61.42, 1019.43,  357.43],
       [  24.16,   44.16, 1017.91,  213.92],
       [  26.07,   63.36, 1008.35,   47.59],
       [  26.67,   71.17, 1005.  ,  183.13],
       [  21.2 ,   62.95, 1005.4 ,  164.74],
       [  23.48,   57.7 , 1016.02,  200.36],
       [  14.11,  145.  , 1032.36,  169.57],
       [  21.23,   79.61, 1015.26,  214.53],
       [  23.43,   68.29, 1015.9 ,  239.43],
       [  23.49,   49.41, 1020.74,  248.26],
       [  20.39,   66.77, 1022.7 ,  135.43],
       [  28.65,   66.88, 1001.41,  206.13],
       [  27.49,   58.6 , 1010.83,  269.37],
       [  22.7 ,   67.34, 1014.21,  256.07],
       [  20.18,   58.65, 1003.69,  157.29],
       [  18.98,   60.14, 1012.57,  259.56],
       [  23.37,   61.66, 1020.33,  170.31],
       [  24.44,   73.13, 1014.93,  150.13],
       [  22.25,   64.53, 1015.23,  134.64],
       [  31.15,   69.2 , 1016.1 ,  172.49],
       [  23.54,   55.89, 1019.6 ,  191.45],
       [  27.22,   68.87, 1003.77,  237.13],
       [  25.68,   61.05, 1024.74,  224.86],
       [  19.63,   61.8 , 1009.24,  151.25],
       [  18.85,   70.17,  995.24,  296.15],
       [  25.89,   67.36, 1019.98,  254.72],
       [  24.99,   63.58, 1017.92,  152.12],
       [  25.41,   59.67, 1009.71,  241.32],
       [  20.39,   85.01, 1013.45,  161.04],
       [  25.99,   75.59, 1021.21,  151.75],
       [  23.71,   76.28,  994.75,  112.65],
       [  24.09,   56.12, 1023.69,  271.39],
       [  20.12,   68.53, 1028.3 ,  200.98],
       [  20.46,   54.16, 1015.76,  167.07],
       [  15.49,   47.96, 1006.34,  124.9 ],
       [  24.87,   74.16,  999.13,  268.79],
       [  27.74,   66.6 , 1012.05,  162.86],
       [  23.1 ,   57.75, 1030.03,  193.04],
       [  28.72,   65.36, 1027.03,  145.8 ],
       [  25.73,   75.79, 1022.59,  272.33],
       [  23.39,   68.65, 1038.43,  188.31],
       [  20.65,   69.15, 1017.63,  183.96],
       [  25.14,   69.54, 1010.53,  272.1 ],
       [  28.13,   72.93, 1010.21,  209.19],
       [  27.82,   64.93, 1014.36,  259.2 ],
       [  28.02,   64.87, 1001.37,  223.19],
       [  26.14,   84.97, 1003.59,  142.31],
       [  28.35,   70.63, 1013.92,  294.85],
       [  28.31,   70.29, 1023.91,   95.36],
       [  30.68,   36.33, 1010.46,  272.59],
       [  22.59,   43.44, 1010.87,  203.83],
       [  22.71,   85.93, 1025.59,  167.36],
       [  21.09,   70.41, 1019.1 ,  170.16],
       [  25.43,   39.35, 1019.28,  292.26],
       [  21.61,   68.02, 1007.2 ,  151.72],
       [  27.65,   68.96, 1000.46,  197.4 ],
       [  21.92,   64.82, 1005.78,  264.59],
       [  28.52,   47.73, 1016.48,  240.7 ],
       [  23.61,   46.69, 1020.43,  152.77],
       [  25.83,   60.66, 1019.32,  224.08],
       [  24.67,   79.33, 1013.73,  206.13],
       [  22.01,   68.61, 1001.87,  244.74],
       [  22.38,   76.48,  993.85,  144.6 ],
       [  33.01,   73.24, 1014.36,  260.24],
       [  17.94,   70.38, 1004.73,  160.59],
       [  22.17,   83.86, 1008.63,  140.71],
       [  27.02,   68.16, 1016.28,  257.73],
       [  28.57,   63.09, 1002.79,  179.  ],
       [  28.24,   55.1 ,  995.94,  292.05],
       [  23.95,   56.47, 1020.04,  215.  ],
       [  24.69,   60.21, 1019.33,  297.43],
       [  27.26,   77.58, 1022.12,  230.53],
       [  30.86,   76.  , 1011.94,  224.01],
       [  20.14,   74.74, 1018.59,  154.59],
       [  24.52,   73.93, 1006.8 ,  202.15],
       [  28.17,   66.03, 1011.82,  351.47],
       [  23.81,   72.72, 1019.47,  223.44],
       [  31.19,   55.13, 1011.04,  264.98],
       [  20.58,   53.8 , 1016.58,  182.62],
       [  25.  ,   67.47, 1021.68,  204.79],
       [  18.41,   65.29, 1013.25,  174.71],
       [  18.72,   47.32, 1013.88,  200.63],
       [  22.33,   67.42, 1014.41,  101.2 ],
       [  30.48,   93.57, 1015.93,  306.24],
       [  25.81,   63.18, 1017.6 ,  116.56],
       [  26.66,   62.41, 1024.83,  189.47],
       [  27.11,   55.41, 1020.03,  227.75],
       [  30.57,   71.26, 1002.88,  359.97],
       [  24.37,   58.38, 1010.1 ,  132.82],
       [  20.95,   61.65, 1014.3 ,  256.38],
       [  24.87,   68.24, 1006.61,  214.18]])

## `Partie 5 – Mise à l'échelle`

### `5.1: Sélection de StandardScaler pour mettre à l’échelle les transformés de l’imputation`

In [40]:
from sklearn.preprocessing import StandardScaler

# Instanciation de l'objet scaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
x_test_scaled = scaler.transform(X_test_imputed)

### `5.2: Qu’est ce qui justifie la standardisation ?`

On applique la `standardisation` pour que les valeurs des differentes variable partage une echèlle comparable, et comme notre dataset contient des outliers il est indispensable de mettre à l'échelle les valeur d'oú l'importance de la standardisation,. De plus certains algo sont sensibles à l'echelle des variables.

### `5.3: On donne les paramètres (moyennes et écart-types) du scaleur sur X_train_imputed`

`Moyennes`

In [60]:
means = scaler.mean_
print(f"Moyennes de chaque features:")
for col, med in zip(X_train.columns, means):
     print(f"{col}  --- : {med:.4f}")

Moyennes de chaque features:
temperature  --- : 24.9269
humidite  --- : 64.6353
pression  --- : 1011.9900
consommation  --- : 208.4475

`Ecart-types`

In [59]:
ecart_types = scaler.mean_
print(f"Ecart-types de chaque features:")
for col, med in zip(X_train.columns, ecart_types):
     print(f"{col}  --- : {med:.4f}")

Ecart-types de chaque features:
temperature  --- : 24.9269
humidite  --- : 64.6353
pression  --- : 1011.9900
consommation  --- : 208.4475

### `5.4: On déterminer X_train_scaled et X_test_scaled, les transformés de X_train_imputed et X_test_imputed`

In [64]:
print(X_train_scaled)

[[ 8.16891196  1.67353001  1.35520087  0.85676261]
 [ 0.30793852  1.15385897  0.43494622 -0.23105564]
 [ 0.56674595  1.09534639  0.16390605  1.71092738]
 ...
 [-0.79501653 -1.17970203 -0.84333784 -0.68405453]
 [ 0.32486984  0.41203847 -0.81220485  0.49204181]
 [ 1.88497073 -1.12614814 -0.17764119 -0.176523  ]]

In [63]:
print(x_test_scaled)

[[-1.36826290e+00 -6.19369700e-01 -7.55432917e-01 -9.70350911e-01]
 [ 2.49888252e-01 -1.83004703e-01  1.64821727e-02  2.73911236e-01]
 [-1.37567035e-02  5.29063633e-01  1.96870396e-01 -3.69546960e-01]
 [ 2.02284011e+00 -1.40879365e+00 -1.94123368e-01  2.00194812e+00]
 [ 1.31898064e+00  1.33359920e-01 -5.96105247e-01  6.44301270e-01]
 [ 7.07034092e-01 -6.57055768e-01  2.74702879e-02 -4.82616144e-03]
 [ 2.69238340e-01  2.51376817e-01 -5.58562520e-02  6.14740258e-01]
 [ 9.02953738e-01 -2.85673205e+00  9.64207105e-01 -8.85312382e-01]
 [ 2.25247124e-02  1.45138056e+00  1.43852741e+00  8.68264745e-02]
 [-1.01996130e+00  7.31378314e-01 -9.01025442e-01 -8.66684895e-01]
 [-1.61754646e-02  4.10054998e-01 -7.33456686e-01  1.09797507e+00]
 [ 2.37794447e-01 -1.53077750e+00  4.19379728e-01 -9.55339248e-02]
 [ 1.10612967e+00  1.66956306e+00  3.19571016e-01  6.49025633e-01]
 [ 5.81258517e-01  2.46097048e+00 -9.16591939e-01  1.85994728e+00]
 [-4.75740066e-01 -2.20515977e+00 -4.76151657e-02 -8.87877036e-01]
 [-3.11264314e-01 -1.57143878e+00 -1.62440969e+00  1.88602745e-01]
 [-1.01754254e+00  1.05468511e+00 -1.31491111e+00  3.01717485e-01]
 [-5.16859004e-01  3.67410237e-01  1.30026029e-01 -1.25394765e+00]
 [ 1.44959374e+00  2.53360294e-01 -2.08774188e-01  1.63776725e+00]
 [ 2.74075862e-01  1.23914849e+00  9.04688148e-01 -1.35099956e+00]
 [ 1.21981144e+00  3.98154134e-01 -4.39524606e-01  7.95345894e-01]
 [-1.51626084e-01 -5.83667109e-01  1.06310014e+00  4.91501883e-01]
 [ 4.42935619e-02 -4.52757610e-01  1.50995016e+00 -3.75891104e-01]
 [-1.59804520e+00  2.51376817e-01  1.24623539e+00 -8.71650538e-02]
 [-1.66138650e-01  4.63608884e-01  1.66103674e+00 -1.03581708e+00]
 [ 1.31656188e+00 -8.45870406e-03 -1.34421275e+00  1.39466504e+00]
 [ 1.28511799e+00 -2.55401623e-01 -2.41738533e-01  1.23160704e+00]
 [ 2.42631969e-01 -3.55567224e-01  8.88205975e-02 -4.83201628e-01]
 [-2.24188916e-01  1.49700054e+00 -1.70315785e+00 -1.24517384e+00]
 [-1.41951040e-01 -3.18872895e-01  6.81263139e-01  2.01099190e+00]
 [-1.85488739e-01 -2.03061377e+00  5.42080348e-01  7.38682226e-02]
 [ 2.76494624e-01 -1.26475601e-01 -3.33306160e-01 -2.17128390e+00]
 [ 4.21620287e-01  6.48072269e-01 -6.40057708e-01 -3.41740711e-01]
 [-9.01442012e-01 -1.67136885e-01 -6.03430657e-01 -5.89972224e-01]
 [-3.49964491e-01 -6.87799665e-01  3.69017534e-01 -1.09167086e-01]
 [-2.61634360e+00  7.97007857e+00  1.86523255e+00 -5.24776019e-01]
 [-8.94185729e-01  1.48509967e+00  2.99426138e-01  8.21021118e-02]
 [-3.62058296e-01  3.62451543e-01  3.58029419e-01  4.18206771e-01]
 [-3.47545730e-01 -1.50995099e+00  8.01216730e-01  5.37395692e-01]
 [-1.09736166e+00  2.11707272e-01  9.80689277e-01 -9.85603853e-01]
 [ 9.00534977e-01  2.22616397e-01 -9.68785486e-01 -3.12825924e-02]
 [ 6.19958694e-01 -5.98543189e-01 -1.06218446e-01  8.22342252e-01]
 [-5.38627853e-01  2.68236374e-01  2.03280130e-01  6.42816471e-01]
 [-1.14815564e+00 -5.93584496e-01 -7.60011298e-01 -6.90533658e-01]
 [-1.43840697e+00 -4.45815440e-01  5.31092232e-02  6.89925115e-01]
 [-3.76570862e-01 -2.95071168e-01  7.63674003e-01 -5.14787367e-01]
 [-1.17763429e-01  8.42453040e-01  2.69208821e-01 -7.87180621e-01]
 [-6.47472101e-01 -1.04421813e-02  2.96679109e-01 -9.96267414e-01]
 [ 1.50522524e+00  4.52699759e-01  3.76342944e-01 -4.85361336e-01]
 [-3.35451924e-01 -8.67304357e-01  6.96829636e-01 -2.29435861e-01]
 [ 5.54652145e-01  4.19972384e-01 -7.52685888e-01  3.87160959e-01]
 [ 1.82162942e-01 -3.55567224e-01  1.16748723e+00  2.21538302e-01]
 [-1.28118750e+00 -2.81186827e-01 -2.51810972e-01 -7.72062660e-01]
 [-1.46985086e+00  5.48898406e-01 -1.53375774e+00  1.18382349e+00]
 [ 2.32956924e-01  2.70219851e-01  7.31625334e-01  6.24593929e-01]
 [ 1.52684292e-02 -1.04657351e-01  5.42996024e-01 -7.60319244e-01]
 [ 1.16856394e-01 -4.92427155e-01 -2.08774188e-01  4.43718329e-01]
 [-1.09736166e+00  2.02063853e+00  1.33688734e-01 -6.39915487e-01]
 [ 2.57144535e-01  1.08642074e+00  8.44253514e-01 -7.65313570e-01]
 [-2.94332986e-01  1.15485071e+00 -1.57862588e+00 -1.29309237e+00]
 [-2.02420066e-01 -8.44494369e-01  1.07134123e+00  8.49608574e-01]
 [-1.16266821e+00  3.86253271e-01  1.49346798e+00 -1.00798215e-01]
 [-1.08043033e+00 -1.03887514e+00  3.45209951e-01 -5.58521467e-01]
 [-2.28255458e+00 -1.65375309e+00 -5.17357088e-01 -1.12773968e+00]
 [-1.37567035e-02  9.44602119e-01 -1.17755967e+00  8.14513308e-01]
 [ 6.80427720e-01  1.94847715e-01  5.49405758e-03 -6.15348801e-01]
 [-4.41877411e-01 -6.82840972e-01  1.65187998e+00 -2.07973756e-01]
 [ 9.17466304e-01  7.18721250e-02  1.37717710e+00 -8.45627736e-01]
 [ 1.94256748e-01  1.10625552e+00  9.70616838e-01  8.62296862e-01]
 [-3.71733340e-01  3.98154134e-01  2.42104804e+00 -2.71820144e-01]
 [-1.03447387e+00  4.47741066e-01  5.16441412e-01 -3.30537222e-01]
 [ 5.15498451e-02  4.86418872e-01 -1.33688734e-01  8.59192281e-01]
 [ 7.74759402e-01  8.22618268e-01 -1.62990375e-01  1.00218355e-02]
 [ 6.99777809e-01  2.92273639e-02  2.17015274e-01  6.85065771e-01]
 [ 7.48153030e-01  2.32769321e-02 -9.72448191e-01  1.98996343e-01]
 [ 2.93425951e-01  2.01667158e+00 -7.69168061e-01 -8.92736381e-01]
 [ 8.27972145e-01  5.94518383e-01  1.76725519e-01  1.16627585e+00]
 [ 8.18297101e-01  5.60799269e-01  1.09148611e+00 -1.52647589e+00]
 [ 1.39154347e+00 -2.80714512e+00 -1.40098468e-01  8.65806389e-01]
 [-5.65234225e-01 -2.10201895e+00 -1.02555741e-01 -6.23284043e-02]
 [-5.36209092e-01  2.11187849e+00  1.24531972e+00 -5.54606995e-01]
 [-9.28048384e-01  5.72700133e-01  6.51045823e-01 -5.16812094e-01]
 [ 1.21693916e-01 -2.50764005e+00  6.67527996e-01  1.13131557e+00]
 [-8.02272809e-01  3.35674600e-01 -4.38608930e-01 -7.65718516e-01]
 [ 6.58658871e-01  4.28898032e-01 -1.05577473e+00 -1.49121696e-01]
 [-7.27291216e-01  1.83182389e-02 -5.68634959e-01  7.57820956e-01]
 [ 8.69091083e-01 -1.67656308e+00  4.11138642e-01  4.35349458e-01]
 [-3.18520597e-01 -1.77970390e+00  7.72830766e-01 -7.51545428e-01]
 [ 2.18444358e-01 -3.94245031e-01  6.71190701e-01  2.11009722e-01]
 [-6.21319247e-02  1.45733099e+00  1.59327670e-01 -3.12825924e-02]
 [-7.05522366e-01  3.94187180e-01 -9.26664378e-01  4.89882102e-01]
 [-6.16028207e-01  1.17468548e+00 -1.66103674e+00 -8.61825551e-01]
 [ 1.95511480e+00  8.53362165e-01  2.17015274e-01  6.99103877e-01]
 [-1.68995812e+00  5.69724917e-01 -6.64780967e-01 -6.45989667e-01]
 [-6.66822189e-01  1.90658859e+00 -3.07667224e-01 -9.14333467e-01]
 [ 5.06276924e-01  3.49558941e-01  3.92825117e-01  6.65223448e-01]
 [ 8.81184888e-01 -1.53252544e-01 -8.42422162e-01 -3.97488191e-01]
 [ 8.01365773e-01 -9.45651709e-01 -1.46966040e+00  1.12848095e+00]
 [-2.36282721e-01 -8.09783517e-01  7.37119391e-01  8.84462560e-02]
 [-5.72944026e-02 -4.38873269e-01  6.72106377e-01  1.20110116e+00]
 [ 5.64327190e-01  1.28377673e+00  9.27580054e-01  2.98072977e-01]
 [ 1.43508117e+00  1.12708203e+00 -4.57838131e-03  2.10064849e-01]
 [-1.15783068e+00  1.00212296e+00  6.04346333e-01 -7.26978742e-01]
 [-9.84133406e-02  9.21792131e-01 -4.75235980e-01 -8.50053451e-02]
 [ 7.84434446e-01  1.38318613e-01 -1.55664965e-02  1.93054275e+00]
 [-2.70145376e-01  8.01791756e-01  6.84925844e-01  2.02370887e-01]
 [ 1.51490029e+00 -9.42676493e-01 -8.69892450e-02  7.63085246e-01]
 [-1.05140520e+00 -1.07457773e+00  4.20295405e-01 -3.48624782e-01]
 [ 1.76871902e-02  2.81128976e-01  8.87290299e-01 -4.93701524e-02]
 [-1.57627635e+00  6.49299545e-02  1.15375209e-01 -4.55395379e-01]
 [-1.50129475e+00 -1.71722436e+00  1.73062814e-01 -1.05522577e-01]
 [-6.28122012e-01  2.76170283e-01  2.21593656e-01 -1.44764652e+00]
 [ 1.34316825e+00  2.86956680e+00  3.60776447e-01  1.32002011e+00]
 [ 2.13606836e-01 -1.44326896e-01  5.13694383e-01 -1.24031449e+00]
 [ 4.19201526e-01 -2.20690771e-01  1.17572832e+00 -2.56162256e-01]
 [ 5.28045774e-01 -9.14907812e-01  7.36203715e-01  2.60548039e-01]
 [ 1.36493710e+00  6.56997917e-01 -8.34181075e-01  2.04527728e+00]
 [-1.34694756e-01 -6.20361439e-01 -1.73062814e-01 -1.02083410e+00]
 [-9.61911039e-01 -2.96062907e-01  2.11521217e-01  6.47000906e-01]
 [-1.37567035e-02  3.57492850e-01 -4.92633829e-01  7.73777491e-02]]

## `Partie 6: Ecodage de la Target`

In [79]:

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['OK', 'ALERTE', 'ERREUR']])

y_train_encoded = encoder.fit_transform(y_train).ravel()
y_test_encoded = encoder.transform(y_test).ravel()

""" 
Encodage avec pandas
mapping_cible = {'OK': 0, 'ALERTE': 1, 'ERREUR': 2}

# Appliquer sur votre variable cible
y_train_encoded = y_train['etat'].map(mapping_cible)
y_test_encoded = y_test['etat'].map(mapping_cible) """

y_train_encoded

array([2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 2., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1.])

## `Partie 7 – Entrainement et prédiction d’un modèle`

### `7.1: Sélection du modèle KNN (k plus proches voisins) avec 5, le nombre de voisins à prendre en compte`

In [83]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

### `7.2: Entrainement du modèle`

In [84]:
import time

temps_debut = time.time()
print(f"Début de l'entraînement : {time.strftime('%H:%M:%S', time.localtime(temps_debut))}")

knn.fit(X_train_scaled, y_train_encoded)

temps_fin = time.time()
print(f"Fin de l'entraînement   : {time.strftime('%H:%M:%S', time.localtime(temps_fin))}")

# 5. Calculer et afficher la durée totale
print(f"Durée totale de l'entraînement : { temps_fin - temps_debut:.4f} secondes")

Début de l'entraînement : 15:08:37
Fin de l'entraînement   : 15:08:37
Durée totale de l'entraînement : 0.0047 secondes

### `7.3: On détermine y_pred, la prédiction du modèle avec l’ensemble de test`

In [100]:
from sklearn.metrics import classification_report, accuracy_score

y_pred_encoded = knn.predict(x_test_scaled)

### `7.4: Affichage de quelques prédictions`

In [101]:
y_pred_texte = encoder.inverse_transform(y_pred_encoded.reshape(-1, 1)).ravel()
y_test_texte = encoder.inverse_transform(y_test_encoded.reshape(-1, 1)).ravel()

In [102]:
print(y_pred_texte[:5])

['OK' 'OK' 'OK' 'ALERTE' 'OK']

### `7.5: Comparaison des prédictions avec les vraies valeurs`

In [104]:
exactitude = accuracy_score(y_test_texte, y_pred_texte)
print(f"Taux de prédictions correctes : {exactitude * 100:.2f}%\n")

# 3. Boucle pour afficher les 10 premières valeurs
print(f"{'Index':<6} | {'Valeur Réelle':<15} | {'Valeur Prédite':<15} | Statut")
print("-" * 55)

for i in range(10):
    reelle = y_test_texte[i]
    predite = y_pred_texte[i]
    statut = "✅ Correct" if reelle == predite else "❌ Erreur"
    
    print(f"{i:<6} | {reelle:<15} | {predite:<15} | {statut}")

Taux de prédictions correctes : 96.67%

Index  | Valeur Réelle   | Valeur Prédite  | Statut
-------------------------------------------------------
0      | OK              | OK              | ✅ Correct
1      | OK              | OK              | ✅ Correct
2      | OK              | OK              | ✅ Correct
3      | ALERTE          | ALERTE          | ✅ Correct
4      | OK              | OK              | ✅ Correct
5      | OK              | OK              | ✅ Correct
6      | OK              | OK              | ✅ Correct
7      | OK              | OK              | ✅ Correct
8      | OK              | OK              | ✅ Correct
9      | OK              | OK              | ✅ Correct