# `=== Atelier Scikit-learn ===`

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")

# Exploration du dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

## `Partie 1 – Gestion des doublons`

### `1.1: Vérification de l’existence de doublons dans df`

In [10]:
print(f" Duplications: {df.duplicated().sum()}")

 Duplications: 5

### `1.2: Suppression des doublons`

In [13]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

### `1.3: gestion des Valeurs manquantes`

In [14]:
df.isna().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     6
humidite        5
pression        5
consommation    5
etat            4
dtype: int64

In [15]:
# Statistiques descriptives
df.describe()

       temperature    humidite     pression  consommation
count   594.000000  595.000000   595.000000    595.000000
mean     24.896212   64.863395  1012.241059    208.693294
std       4.068454   10.760478    10.623413     72.320179
min     -18.500000   28.520000   850.000000     18.120000
25%      22.597500   58.090000  1006.890000    160.500000
50%      24.870000   65.370000  1012.960000    206.130000
75%      27.295000   71.590000  1017.835000    254.265000
max      58.700000  145.000000  1038.430000    875.000000

In [16]:
# Gestion des veleurs manquantes pour la variable numeriques
# colonne température
df['temperature'] = df['temperature'].fillna(df['temperature'].median())
# Colonne consommation
df['consommation'] = df['consommation'].fillna(df['consommation'].median())
# Colonne humidite
df['humidite'] = df['humidite'].fillna(df['humidite'].median())
# Colonne pression
df['pression'] = df['pression'].fillna(df['pression'].median())
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     600 non-null    str
 1   date_heure    600 non-null    str
 2   id_capteur    600 non-null    str
 3   batiment      600 non-null    str
 4   temperature   600 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          596 non-null    str
dtypes: float64(4), str(5)
memory usage: 46.9 KB

In [17]:
# Gestion des veleurs manquantes pour la variable numeriques
df["etat"].mode()

0    OK
Name: etat, dtype: str

In [18]:
df["etat"] = df["etat"].fillna("OK")
df.isnull().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     0
humidite        0
pression        0
consommation    0
etat            0
dtype: int64

## `Partie 2 – Sélection de y (cible) et X (caractéristiques)`

### `2.1: On définit "etat" comme la cible ou valeur à prédire et "temperature", "humidite", "pression" et "consommation" comme caractéristiques ou variables explicatives`

`Selection des features`

In [25]:
X = df[['temperature', 'humidite', 'pression', 'consommation']]

`Selection des labels`

In [26]:
y = df[['etat']]

### `2.2: Affichage des cinq premières lignes de X et de y`

In [27]:
X.head()

   temperature  humidite  pression  consommation
0        25.46     58.06   1008.95        287.28
1        24.00     79.73    993.39        116.20
2        25.82     54.47   1010.32        288.50
3        28.23     69.39   1019.62        136.65
4        20.58     53.80   1016.58        182.62

In [28]:
y.head()

  etat
0   OK
1   OK
2   OK
3   OK
4   OK

### `2.3: Quel est le type du problème de machine learning ?`

Le type de problème en question est un problème de classification, l'objectif est de classer les enreigistrements dans les classe: `OK`, `ALERTE` et `ERREUR` en fontion des valeurs de la temperature, de l'humidité, de la pression et de la consommation

## `Partie 3 – Découpage Train/Test`

#### `3.1:` Division de `X `en deux ensembles distincts : un pour l'entraînement `(train)` et un pour le test `(test)`. Avec les conditions suivantes : `20%` des données serviront au test ; garantir la `reproductibilité` du découpage ; conserver les mêmes `proportions de classes` dans l'ensemble de `train` et de `test` que dans les données d'origine`

In [33]:
from sklearn.model_selection import train_test_split

# Division en train et test des features et labels
X_train, X_test, y_train, y_test = train_test_split(
     X,                  # Features
     y,                  # Target
     test_size=0.2,      # 20% des données pour le test
     random_state=42,    # Garantir la reproductibilité du découpage
     stratify=y          # conserver les meme proportions de classe dans train et test
)

## `Partie 4 – Gestion des valeurs manquantes`

### `4.1: Vérification de l’existence de valeurs manquantes`

In [29]:
X.isnull().sum()

temperature     0
humidite        0
pression        0
consommation    0
dtype: int64

### `4.2: Sélection de SimpleImputer avec la médiane`

In [34]:
from sklearn.impute import SimpleImputer

# Instanciation de l'imputeur
imputer = SimpleImputer(strategy="median")
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

### `4.3: Qu’est ce qui justifie le choix de la médiane ?`

Le dataset en question contient des outliers (valeurs abérantes) et cela influx sur le calcul de la moyenne et de la variance, et pas sur la mediane; ce qui justifie le choix de la médiane

### `4.4: Les paramètres (médianes) de l’imputeur sur X_train`

In [39]:
imputer

SimpleImputer(strategy='median')

### `4.5: On déterminer X_train_imputed et X_test_imputed, les transformés de X_train et X_test`

In [37]:
X_train_imputed

array([[  58.7 ,   81.51, 1026.79,  271.92],
       [  26.2 ,   76.27, 1016.74,  191.33],
       [  27.27,   75.68, 1013.78,  335.2 ],
       ...,
       [  21.64,   52.74, 1002.78,  157.77],
       [  26.27,   68.79, 1003.12,  244.9 ],
       [  32.72,   53.28, 1010.05,  195.37]], shape=(480, 4))

In [38]:
X_test_imputed

array([[  19.27,   58.39, 1003.74,  136.56],
       [  25.96,   62.79, 1012.17,  228.74],
       [  24.87,   69.97, 1014.14,  181.07],
       [  33.29,   50.43, 1009.87,  356.76],
       [  30.38,   65.98, 1005.48,  256.18],
       [  27.85,   58.01, 1012.29,  208.09],
       [  26.04,   67.17, 1011.38,  253.99],
       [  28.66,   35.83, 1022.52,  142.86],
       [  25.02,   79.27, 1027.7 ,  214.88],
       [  20.71,   72.01, 1002.15,  144.24],
       [  24.86,   68.77, 1003.98,  289.79],
       [  25.91,   49.2 , 1016.57,  201.37],
       [  29.5 ,   81.47, 1015.48,  256.53],
       [  27.33,   89.45, 1001.98,  346.24],
       [  22.96,   42.4 , 1011.47,  142.67],
       [  23.64,   48.79,  994.25,  222.42],
       [  20.72,   75.27,  997.63,  230.8 ],
       [  22.79,   68.34, 1013.41,  115.55],
       [  30.92,   67.19, 1009.71,  329.78],
       [  26.06,   77.13, 1021.87,  108.36],
       [  29.97,   68.65, 1007.19,  267.37],
       [  24.3 ,   58.75, 1023.6 ,  244.86],
       [  25.11,   60.07, 1028.48,  180.6 ],
       [  18.32,   67.17, 1025.6 ,  201.99],
       [  24.24,   69.31, 1030.13,  131.71],
       [  30.37,   64.55,  997.31,  311.77],
       [  30.24,   62.06, 1009.35,  299.69],
       [  25.93,   61.05, 1012.96,  172.65],
       [  24.  ,   79.73,  993.39,  116.2 ],
       [  24.34,   61.42, 1019.43,  357.43],
       [  24.16,   44.16, 1017.91,  213.92],
       [  26.07,   63.36, 1008.35,   47.59],
       [  26.67,   71.17, 1005.  ,  183.13],
       [  21.2 ,   62.95, 1005.4 ,  164.74],
       [  23.48,   57.7 , 1016.02,  200.36],
       [  14.11,  145.  , 1032.36,  169.57],
       [  21.23,   79.61, 1015.26,  214.53],
       [  23.43,   68.29, 1015.9 ,  239.43],
       [  23.49,   49.41, 1020.74,  248.26],
       [  20.39,   66.77, 1022.7 ,  135.43],
       [  28.65,   66.88, 1001.41,  206.13],
       [  27.49,   58.6 , 1010.83,  269.37],
       [  22.7 ,   67.34, 1014.21,  256.07],
       [  20.18,   58.65, 1003.69,  157.29],
       [  18.98,   60.14, 1012.57,  259.56],
       [  23.37,   61.66, 1020.33,  170.31],
       [  24.44,   73.13, 1014.93,  150.13],
       [  22.25,   64.53, 1015.23,  134.64],
       [  31.15,   69.2 , 1016.1 ,  172.49],
       [  23.54,   55.89, 1019.6 ,  191.45],
       [  27.22,   68.87, 1003.77,  237.13],
       [  25.68,   61.05, 1024.74,  224.86],
       [  19.63,   61.8 , 1009.24,  151.25],
       [  18.85,   70.17,  995.24,  296.15],
       [  25.89,   67.36, 1019.98,  254.72],
       [  24.99,   63.58, 1017.92,  152.12],
       [  25.41,   59.67, 1009.71,  241.32],
       [  20.39,   85.01, 1013.45,  161.04],
       [  25.99,   75.59, 1021.21,  151.75],
       [  23.71,   76.28,  994.75,  112.65],
       [  24.09,   56.12, 1023.69,  271.39],
       [  20.12,   68.53, 1028.3 ,  200.98],
       [  20.46,   54.16, 1015.76,  167.07],
       [  15.49,   47.96, 1006.34,  124.9 ],
       [  24.87,   74.16,  999.13,  268.79],
       [  27.74,   66.6 , 1012.05,  162.86],
       [  23.1 ,   57.75, 1030.03,  193.04],
       [  28.72,   65.36, 1027.03,  145.8 ],
       [  25.73,   75.79, 1022.59,  272.33],
       [  23.39,   68.65, 1038.43,  188.31],
       [  20.65,   69.15, 1017.63,  183.96],
       [  25.14,   69.54, 1010.53,  272.1 ],
       [  28.13,   72.93, 1010.21,  209.19],
       [  27.82,   64.93, 1014.36,  259.2 ],
       [  28.02,   64.87, 1001.37,  223.19],
       [  26.14,   84.97, 1003.59,  142.31],
       [  28.35,   70.63, 1013.92,  294.85],
       [  28.31,   70.29, 1023.91,   95.36],
       [  30.68,   36.33, 1010.46,  272.59],
       [  22.59,   43.44, 1010.87,  203.83],
       [  22.71,   85.93, 1025.59,  167.36],
       [  21.09,   70.41, 1019.1 ,  170.16],
       [  25.43,   39.35, 1019.28,  292.26],
       [  21.61,   68.02, 1007.2 ,  151.72],
       [  27.65,   68.96, 1000.46,  197.4 ],
       [  21.92,   64.82, 1005.78,  264.59],
       [  28.52,   47.73, 1016.48,  240.7 ],
       [  23.61,   46.69, 1020.43,  152.77],
       [  25.83,   60.66, 1019.32,  224.08],
       [  24.67,   79.33, 1013.73,  206.13],
       [  22.01,   68.61, 1001.87,  244.74],
       [  22.38,   76.48,  993.85,  144.6 ],
       [  33.01,   73.24, 1014.36,  260.24],
       [  17.94,   70.38, 1004.73,  160.59],
       [  22.17,   83.86, 1008.63,  140.71],
       [  27.02,   68.16, 1016.28,  257.73],
       [  28.57,   63.09, 1002.79,  179.  ],
       [  28.24,   55.1 ,  995.94,  292.05],
       [  23.95,   56.47, 1020.04,  215.  ],
       [  24.69,   60.21, 1019.33,  297.43],
       [  27.26,   77.58, 1022.12,  230.53],
       [  30.86,   76.  , 1011.94,  224.01],
       [  20.14,   74.74, 1018.59,  154.59],
       [  24.52,   73.93, 1006.8 ,  202.15],
       [  28.17,   66.03, 1011.82,  351.47],
       [  23.81,   72.72, 1019.47,  223.44],
       [  31.19,   55.13, 1011.04,  264.98],
       [  20.58,   53.8 , 1016.58,  182.62],
       [  25.  ,   67.47, 1021.68,  204.79],
       [  18.41,   65.29, 1013.25,  174.71],
       [  18.72,   47.32, 1013.88,  200.63],
       [  22.33,   67.42, 1014.41,  101.2 ],
       [  30.48,   93.57, 1015.93,  306.24],
       [  25.81,   63.18, 1017.6 ,  116.56],
       [  26.66,   62.41, 1024.83,  189.47],
       [  27.11,   55.41, 1020.03,  227.75],
       [  30.57,   71.26, 1002.88,  359.97],
       [  24.37,   58.38, 1010.1 ,  132.82],
       [  20.95,   61.65, 1014.3 ,  256.38],
       [  24.87,   68.24, 1006.61,  214.18]])