# `=== Atelier Scikit-learn ===`

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Importation du dataset
df = pd.read_csv("../data/mesures_capteurs.csv")

# Exploration du dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

## `Partie 1 – Gestion des doublons`

### `1.1: Vérification de l’existence de doublons dans df`

In [10]:
print(f" Duplications: {df.duplicated().sum()}")

 Duplications: 5

### `1.2: Suppression des doublons`

In [13]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

### `1.3: gestion des Valeurs manquantes`

In [14]:
df.isna().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     6
humidite        5
pression        5
consommation    5
etat            4
dtype: int64

In [15]:
# Statistiques descriptives
df.describe()

       temperature    humidite     pression  consommation
count   594.000000  595.000000   595.000000    595.000000
mean     24.896212   64.863395  1012.241059    208.693294
std       4.068454   10.760478    10.623413     72.320179
min     -18.500000   28.520000   850.000000     18.120000
25%      22.597500   58.090000  1006.890000    160.500000
50%      24.870000   65.370000  1012.960000    206.130000
75%      27.295000   71.590000  1017.835000    254.265000
max      58.700000  145.000000  1038.430000    875.000000

In [16]:
# Gestion des veleurs manquantes pour la variable numeriques
# colonne température
df['temperature'] = df['temperature'].fillna(df['temperature'].median())
# Colonne consommation
df['consommation'] = df['consommation'].fillna(df['consommation'].median())
# Colonne humidite
df['humidite'] = df['humidite'].fillna(df['humidite'].median())
# Colonne pression
df['pression'] = df['pression'].fillna(df['pression'].median())
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     600 non-null    str
 1   date_heure    600 non-null    str
 2   id_capteur    600 non-null    str
 3   batiment      600 non-null    str
 4   temperature   600 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          596 non-null    str
dtypes: float64(4), str(5)
memory usage: 46.9 KB

In [17]:
# Gestion des veleurs manquantes pour la variable numeriques
df["etat"].mode()

0    OK
Name: etat, dtype: str

In [18]:
df["etat"] = df["etat"].fillna("OK")
df.isnull().sum()

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     0
humidite        0
pression        0
consommation    0
etat            0
dtype: int64

## `Partie 2 – Sélection de y (cible) et X (caractéristiques)`

### `2.1: On définit "etat" comme la cible ou valeur à prédire et "temperature", "humidite", "pression" et "consommation" comme caractéristiques ou variables explicatives`

`Selection des features`

In [25]:
X = df[['temperature', 'humidite', 'pression', 'consommation']]

`Selection des labels`

In [26]:
y = df[['etat']]

### `2.2: Affichage des cinq premières lignes de X et de y`

In [27]:
X.head()

   temperature  humidite  pression  consommation
0        25.46     58.06   1008.95        287.28
1        24.00     79.73    993.39        116.20
2        25.82     54.47   1010.32        288.50
3        28.23     69.39   1019.62        136.65
4        20.58     53.80   1016.58        182.62

In [28]:
y.head()

  etat
0   OK
1   OK
2   OK
3   OK
4   OK

### `2.3: Quel est le type du problème de machine learning ?`

Le type de problème en question est un problème de classification, l'objectif est de classer les enreigistrements dans les classe: `OK`, `ALERTE` et `ERREUR` en fontion des valeurs de la temperature, de l'humidité, de la pression et de la consommation

## `Partie 3 – Découpage Train/Test`

#### `3.1:` Division de `X `en deux ensembles distincts : un pour l'entraînement `(train)` et un pour le test `(test)`. Avec les conditions suivantes : `20%` des données serviront au test ; garantir la `reproductibilité` du découpage ; conserver les mêmes `proportions de classes` dans l'ensemble de `train` et de `test` que dans les données d'origine`

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
     X,                  # Features
     y,                  # Target
     test_size=0.2,      # 20% des données pour le test
     random_state=42,    # Garantir la reproductibilité du découpage
     stratify=y          # conserver les meme proportions de classe dans train et test
)